### ISSUE TITLE
use ubi8-minimal

### ISSUE THREAD

**Issue by goern** [thoth-station/thoth-ci#7]
Shall we try and test if registry.access.redhat.com/ubi8/ubi-minimal is suitable for steps like https://github.com/thoth-station/thoth-ci/blob/3087df33cd932ca6de0b820a98a8e1b9b4294f9f/conditions/retest-comment-check.yaml#L17

**Comment by harshad16** [comment]
definitely I can point to ubi-minimal image.

**Comment by harshad16** [comment]
most of the pipelines are pointing either to ubi-minimal or ubi 
https://github.com/thoth-station/thoth-ci/blob/b74d59e764a3a387e76adb78eb7f5a35461378db/tasks/resource.yaml#L14

will keep reusing the image.
next time will make sure to use pr for closing the issue.
